### ISSUE TITLE
with open(pfam_seq) OSError: [Errno 22] Invalid argument: '|'

### ISSUE THREAD

**Issue by badlammajamma** [ranganathanlab/pySCA#4]
When attempting to run the annotation step:

`python ..\bin\annotateMSA -i PF00034_full_length_sequences.fasta -o PF00034_full_length_sequences.an`

I get the following output/error:

`Beginning annotation
Traceback (most recent call last):
  File "C:\Users\dlamm\pySCA\bin\annotateMSA", line 178, in <module>
    sca.AnnotPfam(
  File "C:\Users\dlamm\AppData\Local\Programs\Python\Python39\lib\site-packages\pysca\scaTools.py", line 180, in AnnotPfam
    with open(pfam_seq) as fp:
OSError: [Errno 22] Invalid argument: '|'`

In settings I have :

` path2pfamseq = r"C:\Users\dlamm\pfamseq.txt"`

Running on:
Windows 10
Python 3.9
pySCA 6.1

**Comment by badlammajamma** [comment]
I have since resolved by explicitly giving path2pfamseq argument in command line as below. Though I would like to know why my original code did not work.

`python ..\bin\annotateMSA -i PF00034_full_length_sequences.fasta -o PF00034_full_length_sequences.an -a pfam -p C:\Users\dlamm\pfamseq.txt`
