### ISSUE TITLE
scaCore.py error "ValueError: pvals < 0, pvals > 1 or pvals contains NaNs"

### ISSUE THREAD

**Issue by Bingbing19** [ranganathanlab/pySCA#5]
Hi, 

I am running scaCore.py with command `./scaCore.py  XXXX.db` and it reports an error as in the following: 
`Computing the sequence projections.`
`Computing the SCA conservation and correlation values.`
`Computing matrix randomizations... `
`Traceback (most recent call last):`
 ` File "./scaCore.py", line 91, in <module>
    Vrand, Lrand, Crand = sca.randomize(msa_num, options.Ntrials, seqw, options.lbda)`
  `File "/path/scaTools.py", line 1231, in randomize
    msa_rand = randAlg(fr01, Mseq)`
  `File "/path/scaTools.py", line 1190, in randAlg
    Maa = np.random.multinomial(Mseq, frq[i,:])`
 ` File "mtrand.pyx", line 4249, in numpy.random.mtrand.RandomState.multinomial`
 ` File "_common.pyx", line 376, in numpy.random._common.check_array_constraint`
 ` File "_common.pyx", line 362, in numpy.random._common._check_array_cons_bounded_0_1
ValueError: pvals < 0, pvals > 1 or pvals contains NaNs`
The XXXX.db used here is a scaProcessMSA.py treated MSA XXXX.fa with all default setting. I have 4 MSA and 1 of them could be processed successfully with scaCore.py but three of them reports the same error like I showed above. Could you please help me with this? Thank you for any inputs in advance.

**Comment by Bingbing19** [comment]
The problem disappear with the newest version of scaTools scripts. I will close the issue. Thank you.
